// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv9BHwQ3BjZfvRGwIk__vidG8RmjrdscQ',
    appId: '1:1034016316021:web:c1ba32f9c62f006decb63c',
    messagingSenderId: '1034016316021',
    projectId: 'our-chat-cc2f5',
    authDomain: 'our-chat-cc2f5.firebaseapp.com',
    storageBucket: 'our-chat-cc2f5.appspot.com',
    measurementId: 'G-S4ERTCYQCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHQ2lZJJRkuXaKegtgSWx4bR-xMMI9Y1k',
    appId: '1:1034016316021:android:70ecba8ebc7c0bd1ecb63c',
    messagingSenderId: '1034016316021',
    projectId: 'our-chat-cc2f5',
    storageBucket: 'our-chat-cc2f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6goQNY1n3dZ49QAUu699yoNC66MIO0OA',
    appId: '1:1034016316021:ios:094142e4fda783a8ecb63c',
    messagingSenderId: '1034016316021',
    projectId: 'our-chat-cc2f5',
    storageBucket: 'our-chat-cc2f5.appspot.com',
    iosClientId: '1034016316021-5naq0fn57f3v8bn5e8074p0rqj9ime38.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6goQNY1n3dZ49QAUu699yoNC66MIO0OA',
    appId: '1:1034016316021:ios:094142e4fda783a8ecb63c',
    messagingSenderId: '1034016316021',
    projectId: 'our-chat-cc2f5',
    storageBucket: 'our-chat-cc2f5.appspot.com',
    iosClientId: '1034016316021-5naq0fn57f3v8bn5e8074p0rqj9ime38.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv9BHwQ3BjZfvRGwIk__vidG8RmjrdscQ',
    appId: '1:1034016316021:web:0b08c41846ba207fecb63c',
    messagingSenderId: '1034016316021',
    projectId: 'our-chat-cc2f5',
    authDomain: 'our-chat-cc2f5.firebaseapp.com',
    storageBucket: 'our-chat-cc2f5.appspot.com',
    measurementId: 'G-WBPN4RHMTG',
  );

}